# glslpp — CI-equivalent recipes
# All recipes use `mise exec --` to ensure Zig 0.15.2 is used.
# Run `just` or `just ci` to execute the full CI pipeline locally.

set dotenv-load := false

# zig wrapper — ensures Zig 0.15.2 via mise
zig := "mise exec -- zig"

# ── default ──────────────────────────────────────────────────────────

default: test

# ── build ────────────────────────────────────────────────────────────

# build the library (debug)
build:
    {{zig}} build

# build in release mode
release:
    {{zig}} build -Doptimize=ReleaseFast

# ── tests ────────────────────────────────────────────────────────────

# run all unit tests (lexer, parser, semantic, codegen, spirv, ir, etc.)
test:
    {{zig}} build test --summary all

# run HLSL backend tests (751 tests)
test-hlsl:
    {{zig}} build test-hlsl --summary all

# run SPIR-V conformance tests against spirv-val (requires Vulkan SDK)
test-conformance:
    {{zig}} build conformance --summary all

# list analyzer false-positive candidates (strict vs tolerate compile)
enumerate-fp:
    {{zig}} build enumerate-fp --summary all

# continuous strict-gate: verify no curated-valid fixtures are rejected (FP regression check)
strict-gate:
    {{zig}} build strict-gate --summary all

# run tests with verbose output
test-verbose:
    {{zig}} build test --summary all 2>&1 | grep -E "passed|failed|leaked|error:"

# ── DXC validation ───────────────────────────────────────────────────

# validate saved HLSL outputs with DXC (requires dxc.exe on PATH)
# -Fo must be a real, writable path on Windows (/dev/null is not a valid dxc
# output target), so compile to throwaway .dxil files and delete them after.
validate-dxc: generate-outputs
    dxc -T ps_6_0 -E main tests/wintty/crt_output.hlsl -Fo tests/wintty/crt_check.dxil
    # NOTE: crt_output.hlsl is regenerated by generate-outputs; focus_output.hlsl is a
    # committed snapshot (its generator, dump_shader.zig, still needs the 0.15.2 migration).
    # TODO: regenerate focus_output.* in-gate once the sibling tools are migrated.
    dxc -T ps_6_0 -E main tests/wintty/focus_output.hlsl -Fo tests/wintty/focus_check.dxil
    rm -f tests/wintty/crt_check.dxil tests/wintty/focus_check.dxil
    @echo "DXC validation: ALL PASSED"

# regenerate saved HLSL outputs from wintty shaders
generate-outputs:
    {{zig}} run -ODebug --dep glslpp -Mroot=tools/dump_crt_hlsl.zig -Mglslpp=src/root.zig

# ── benchmarks ───────────────────────────────────────────────────────

# run wintty shader benchmark (ReleaseFast, 50 iterations)
bench:
    {{zig}} build bench

# ── lint / check ─────────────────────────────────────────────────────

# check compilation without building (fast syntax/type check)
check:
    {{zig}} build 2>&1 | head -1

# ── full CI pipeline ─────────────────────────────────────────────────

# run everything CI would run
ci: test test-hlsl validate-dxc strict-gate
    @echo ""
    @echo "═══════════════════════════════════════"
    @echo "  CI PASSED — all gates green"
    @echo "═══════════════════════════════════════"

# ── cleaning ─────────────────────────────────────────────────────────

clean:
    rm -rf zig-out .zig-cache

# ── utilities ────────────────────────────────────────────────────────

# verify zig version is 0.15.2
check-zig:
    @mise exec -- zig version | grep -q "0.15.2" && echo "Zig 0.15.2 ✓" || (echo "ERROR: expected Zig 0.15.2" && exit 1)

# show test counts summary
summary:
    @echo "Unit tests:" && {{zig}} build test --summary all 2>&1 | grep "passed\|failed\|leaked" | head -1
    @echo "HLSL tests:" && {{zig}} build test-hlsl --summary all 2>&1 | grep "passed" | head -1
