# glslpp — CI-equivalent recipes
# All recipes use `mise exec --` to ensure Zig 0.15.2 is used.
# Run `just` or `just ci` to execute the full CI pipeline locally.

set dotenv-load := false

# zig wrapper — ensures Zig 0.15.2 via mise
zig := "mise exec -- zig"

# ── default ──────────────────────────────────────────────────────────

default: test

# ── build ────────────────────────────────────────────────────────────

# build the library (debug)
build:
    {{zig}} build

# build in release mode
release:
    {{zig}} build -Doptimize=ReleaseFast

# ── tests ────────────────────────────────────────────────────────────

# run all unit tests (lexer, parser, semantic, codegen, spirv, ir, etc.)
test:
    {{zig}} build test --summary all

# run HLSL backend tests (751 tests)
test-hlsl:
    {{zig}} build test-hlsl --summary all

# run SPIR-V conformance tests against spirv-val (requires Vulkan SDK)
test-conformance:
    {{zig}} build conformance --summary all

# list analyzer false-positive candidates (strict vs tolerate compile)
enumerate-fp:
    {{zig}} build enumerate-fp --summary all

# continuous strict-gate: verify no curated-valid fixtures are rejected (FP regression check)
strict-gate:
    {{zig}} build strict-gate --summary all

# ── backend oracle differentials ─────────────────────────────────────
# Every backend output is checked against its reference oracle:
#   SPIR-V → spirv-val   (conformance)        HLSL → dxc            (validate-dxc)
#   GLSL/HLSL/MSL structural → spirv-cross    (test-cross-compare)
#   WGSL → naga                               (test-realworld)

# cross-compiler structural differential: glslpp output vs SPIRV-Cross
test-cross-compare:
    {{zig}} build test-cross-compare --summary all

# validate glslpp WGSL output against naga (real-world shader corpus)
test-realworld:
    {{zig}} build test-realworld --summary all

# all backend oracle differentials in one gate (spirv-val + SPIRV-Cross + naga)
oracle-diff: test-conformance test-cross-compare test-realworld
    @echo ""
    @echo "Backend oracle differentials: ALL PASSED (spirv-val + SPIRV-Cross + naga)"

# large-corpus WGSL<->naga differential: every conformance fixture -> WGSL -> naga.
# Reports naga PASS / REJECT (divergences to fix) / honest-unsupported. Slow
# (naga subprocess per fixture); run on demand, not in `ci`.
wgsl-naga:
    @bash tools/wgsl_naga_sweep.sh

# run tests with verbose output
test-verbose:
    {{zig}} build test --summary all 2>&1 | grep -E "passed|failed|leaked|error:"

# ── DXC validation ───────────────────────────────────────────────────

# validate saved HLSL outputs with DXC (requires dxc.exe on PATH)
# -Fo must be a real, writable path on Windows (/dev/null is not a valid dxc
# output target), so compile to throwaway .dxil files and delete them after.
validate-dxc: generate-outputs
    dxc -T ps_6_0 -E main tests/wintty/crt_output.hlsl -Fo tests/wintty/crt_check.dxil
    # NOTE: crt_output.hlsl is regenerated by generate-outputs; focus_output.hlsl is a
    # committed snapshot (its generator, dump_shader.zig, still needs the 0.15.2 migration).
    # TODO: regenerate focus_output.* in-gate once the sibling tools are migrated.
    dxc -T ps_6_0 -E main tests/wintty/focus_output.hlsl -Fo tests/wintty/focus_check.dxil
    rm -f tests/wintty/crt_check.dxil tests/wintty/focus_check.dxil
    @echo "DXC validation: ALL PASSED"

# regenerate saved HLSL outputs from wintty shaders
generate-outputs:
    {{zig}} run -ODebug --dep glslpp -Mroot=tools/dump_crt_hlsl.zig -Mglslpp=src/root.zig

# ── fuzzing ──────────────────────────────────────────────────────────

# run the structured-GLSL fuzzer (ReleaseFast). Default 100k iters; override:
#   just fuzz 1000000
fuzz count="100000":
    {{zig}} build fuzz -Doptimize=ReleaseFast -- --count {{count}}

# robustness milestone: ≥1M fuzz iterations must be 100% clean (0 fail).
# Verified clean at 1,000,000 iters (seed 1) — see CHANGELOG.
fuzz-million:
    {{zig}} build fuzz -Doptimize=ReleaseFast -- --count 1000000 --seed 1

# ── benchmarks ───────────────────────────────────────────────────────

# run wintty shader benchmark (ReleaseFast, 50 iterations)
bench:
    {{zig}} build bench

# lib-vs-lib: glslpp vs SPIRV-Cross, both IN-PROCESS, same SPIR-V → GLSL/HLSL/MSL
# (honest comparison; needs the Vulkan SDK spirv-cross libs). Override iters:
#   just lib-bench 2000
lib-bench count="1000":
    {{zig}} build lib-bench -- --iters {{count}}

# ── lint / check ─────────────────────────────────────────────────────

# check compilation without building (fast syntax/type check)
check:
    {{zig}} build 2>&1 | head -1

# ── full CI pipeline ─────────────────────────────────────────────────

# run everything CI would run (incl. backend oracle differentials)
ci: test test-hlsl validate-dxc strict-gate oracle-diff
    @echo ""
    @echo "═══════════════════════════════════════"
    @echo "  CI PASSED — all gates green"
    @echo "═══════════════════════════════════════"

# ── cleaning ─────────────────────────────────────────────────────────

clean:
    rm -rf zig-out .zig-cache

# ── utilities ────────────────────────────────────────────────────────

# verify zig version is 0.15.2
check-zig:
    @mise exec -- zig version | grep -q "0.15.2" && echo "Zig 0.15.2 ✓" || (echo "ERROR: expected Zig 0.15.2" && exit 1)

# show test counts summary
summary:
    @echo "Unit tests:" && {{zig}} build test --summary all 2>&1 | grep "passed\|failed\|leaked" | head -1
    @echo "HLSL tests:" && {{zig}} build test-hlsl --summary all 2>&1 | grep "passed" | head -1
