// Generated by glslpp SPIR-V -> HLSL cross-compiler

cbuffer Globals : register(b0)
{
    float3 Globals_iResolution;
    float Globals_iTime;
    float Globals_iTimeDelta;
    float Globals_iFrameRate;
    int Globals_iFrame;
    float Globals_iChannelTime[4];
    float3 Globals_iChannelResolution[4];
    float4 Globals_iMouse;
    float4 Globals_iDate;
    float Globals_iSampleRate;
    float4 Globals_iCurrentCursor;
    float4 Globals_iPreviousCursor;
    float4 Globals_iCurrentCursorColor;
    float4 Globals_iPreviousCursorColor;
    int Globals_iCurrentCursorStyle;
    int Globals_iPreviousCursorStyle;
    int Globals_iCursorVisible;
    float Globals_iTimeCursorChange;
    float Globals_iTimeFocus;
    int Globals_iFocus;
    float3 Globals_iPalette[256];
    float3 Globals_iBackgroundColor;
    float3 Globals_iForegroundColor;
    float3 Globals_iCursorColor;
    float3 Globals_iCursorText;
    float3 Globals_iSelectionForegroundColor;
    float3 Globals_iSelectionBackgroundColor;
};

Texture2D<float4> iChannel0 : register(t0);
SamplerState iChannel0_sampler : register(s0);



void mainImage(out float4 v27, float2 v28)
{
    float3 v29;
    float3 v31 = Globals_iResolution;
    float2 v32 = float2(v31.x, v31.y);
    float2 v33 = v28 / v32;
    float4 v35 = iChannel0.Sample(iChannel0_sampler, v33);
    float3 v36 = float3(v35.x, v35.y, v35.z);
    int v38 = Globals_iFocus;
    bool v39 = v38 > 0;
    v29 = v36;
    if (v39) {
    float v41 = Globals_iTime;
    float v43 = Globals_iTimeFocus;
    float v44 = v41 - v43;
    float v45 = v44 / 3.0;
    float v46 = 1.0 - v45;
    float v47 = max(0.0, v46);
    float v48 = v47 * 0.4;
    float3 v49 = float3(v48, v48, v48);
    float3 v50 = lerp(v36, float3(0.0, 1.0, 0.0), v49);
    v29 = v50;
    float v51 = v28.x;
    bool v52 = v51 < 5.0;
    float v53 = v31.x;
    float v54 = v53 - 5.0;
    bool v55 = v51 > v54;
    bool v56 = v52 || v55;
    float v57 = v28.y;
    bool v58 = v57 < 5.0;
    bool v59 = v56 || v58;
    float v60 = v31.y;
    float v61 = v60 - 5.0;
    bool v62 = v57 > v61;
    bool v63 = v59 || v62;
        if (v63) {
    float v64 = v44 * 2.0;
    float v65 = sin(v64);
    float v66 = v65 * 0.1;
    float v67 = v66 + 0.9;
    float3 v68 = float3(0.0, 1.0, 1.0) * v67;
    v29 = v68;
        }
    } else {
    float3 v69 = v29;
    float3 v70 = float3(0.3, 0.3, 0.3);
    float3 v71 = lerp(v69, float3(1.0, 0.0, 0.0), v70);
    v29 = v71;
    }
    float3 v72 = v29;
    float v73 = v72.x;
    float v74 = v72.y;
    float v75 = v72.z;
    float4 v76 = float4(v73, v74, v75, 1.0);
    v27 = v76;
    return;
}
float4 main(float4 gl_FragCoord : SV_Position) : SV_Target
{
    float4 _fragColor;
    float2 v25 = float2(gl_FragCoord.x, gl_FragCoord.y);
    mainImage(_fragColor, v25);
    return _fragColor;
}
