// Generated by zioshade SPIR-V -> WGSL cross-compiler

@fragment
fn main(@builtin(position) gl_FragCoord: vec4f) -> @location(0) vec4f {
    var v11: vec2f;
    var v12: i32;
    let v14: vec2f = gl_FragCoord.xy;
    let v15: vec2f = v14 / vec2<f32>(128.0);
    let v16: vec2f = (v14 / vec2<f32>(128.0)) - vec2<f32>(0.5);
    let v17: vec2f = ((v14 / vec2<f32>(128.0)) - vec2<f32>(0.5)) * 3.0f;
    v11 = vec2<f32>(0.0);
    v12 = 0;
    var v18: i32 = 0;
    var v25: f32;
    loop {
        if (!(v18 < 16)) { break; }
        let v20: vec2f = v11;
        let v21: f32 = v20.x;
        let v22: f32 = v21 * v21;
        let v23: f32 = v20.y;
        let v24: f32 = v23 * v23;
        v25 = (v21 * v21) - (v23 * v23);
        let v27: f32 = v25 + v17.x;
        let v28: f32 = 2.0f * v21;
        let v29: f32 = (2.0f * v21) * v23;
        let v31: f32 = ((2.0f * v21) * v23) + v17.y;
        let v32: vec2f = vec2f(v27, v31);
        v11 = v32;
        let v33: f32 = dot(v32, v32);
        let v34: bool = v33 > 4.0f;
        if (v33 > 4.0f) { break; }
        let v35: i32 = v12;
        let v36: i32 = v35 + 1;
        v12 = v36;
        continuing {
            let v37: i32 = v18 + 1;
            v18 = v37;
        }
    }
    let v38: i32 = v12;
    let v39: f32 = f32(v38);
    let v40: f32 = v39 / 16.0f;
    let v41: f32 = v40 * v40;
    let v42: f32 = sqrt(v40);
    let v43: vec4f = vec4f(v40, v41, v42, 1.0f);
    return v43;
}
