#!/usr/bin/env bash
# zioshade - static opcode/capability coverage matrix
#
# Emits a per-backend coverage matrix: which SPIR-V Op opcodes zioshade models
# (the Op enum) and which each backend statically handles (.PascalCase emit arms
# in spirv_to_<backend>.zig + the shared spirv_cross_common.zig), plus the
# empirical opcode/capability reach of the real SPIR-V fixtures.
#
# METHODOLOGY (read before trusting a number):
#  * "handled" is a LOWER BOUND: it counts Op enum members that appear as a
#    .PascalCase token in the backend (+common) source. An opcode lowered in a
#    helper via a different style, or only reachable through shared code not
#    captured here, is undercounted. GLSLstd450 extended ops are NOT counted
#    per-backend because GLSL/MSL/WGSL dispatch ExtInst by instruction NAME, not
#    enum arm (only HLSL uses .PascalCase arms there) -- so a per-backend static
#    count would misleadingly read 0. The authoritative coverage proof remains
#    `tools/check_unhandled.zig` (0 unhandled op / 0 unhandled std450 across the
#    conformance corpora) -- this matrix bounds the SCOPE, it does not re-prove it.
#  * The "modelled but not statically handled" set is the candidate honest-error /
#    not-yet-emitted list; module-metadata opcodes (Capability/Extension/
#    ExtInstImport/MemoryModel) are processed structurally, not via per-op arms,
#    so they appear here but are NOT real gaps.
#
# Regenerate: bash tools/coverage_matrix.sh   (or wire a `just coverage-matrix`)
set -euo pipefail
export LC_ALL=C    # comm requires both inputs under one collation; force C everywhere
cd "$(dirname "$0")/.."

T=$(mktemp -d); trap 'rm -rf "$T"' EXIT

# --- universe: Op enum members ---
sed -n '/pub const Op = enum(u16) {/,/^};/p' src/spirv.zig \
  | grep -oE '^[[:space:]]+[A-Z][A-Za-z0-9]* =' | awk '{print $1}' | sort -u > "$T/op.txt"
OPN=$(wc -l < "$T/op.txt" | tr -d ' ')

# --- per-backend handled (backend file + shared common), intersected with Op ---
for f in glsl hlsl msl wgsl; do
  grep -ohE '\.[A-Z][A-Za-z0-9]*' src/spirv_to_$f.zig src/spirv_cross_common.zig \
    | sed 's/^\.//' | sort -u > "$T/tok_$f.txt"
  comm -12 "$T/op.txt" "$T/tok_$f.txt" > "$T/hand_$f.txt"
done
cat "$T"/hand_*.txt | sort | uniq -d > "$T/all4.txt"      # in every backend
cat "$T"/hand_*.txt | sort -u  > "$T/any.txt"              # in >=1 backend
comm -23 "$T/op.txt" "$T/any.txt" > "$T/none.txt"          # modelled, not statically handled

# --- GLSLstd450 universe (for reference; per-backend count omitted, see header) ---
sed -n '/pub const GLSLstd450 = enum(u32) {/,/^};/p' src/spirv.zig \
  | grep -oE '^[[:space:]]+[A-Z][A-Za-z0-9]* =' | awk '{print $1}' | sort -u > "$T/s450.txt"
S450N=$(wc -l < "$T/s450.txt" | tr -d ' ')

# --- empirical reach: real SPIR-V fixtures (spirv-cross's own suite) ---
FIX=$(ls tests/spirv_bins/*.spv 2>/dev/null | wc -l | tr -d ' ')
: > "$T/reach_op_raw.txt"; : > "$T/reach_cap_raw.txt"; ok=0
for spv in tests/spirv_bins/*.spv; do
  [ -f "$spv" ] || continue
  spirv-dis "$spv" 2>/dev/null > "$T/dis.txt" || continue
  ok=$((ok+1))
  grep -oE 'Op[A-Z][A-Za-z0-9]*' "$T/dis.txt" >> "$T/reach_op_raw.txt"
  grep -oE 'OpCapability [A-Za-z0-9_]+' "$T/dis.txt" | awk '{print $2}' >> "$T/reach_cap_raw.txt"
done
sed 's/^Op//' "$T/reach_op_raw.txt" | LC_ALL=C sort -u > "$T/reach_op.txt"
LC_ALL=C sort -u "$T/reach_cap_raw.txt" > "$T/reach_cap.txt"
REACH_OP=$(wc -l < "$T/reach_op.txt" | tr -d ' ')
# OpImage is spelled "OpImage" in zioshade's enum (Op prefix baked into the member),
# so the exercised opcode "Image" is really modelled -- exclude it from the gap list
# rather than rewriting the file (sed -i portability caused a subtle corruption).
comm -23 "$T/reach_op.txt" "$T/op.txt" > "$T/gaps.txt"
{ grep -v '^Image$' "$T/gaps.txt" || true; } > "$T/gaps_real.txt"
REACH_GAP_COUNT=$(wc -l < "$T/gaps_real.txt" | tr -d ' ')
REACH_MODELLED=$(( REACH_OP - REACH_GAP_COUNT ))
REACH_GAP=$(tr '\n' ' ' < "$T/gaps_real.txt")
REACH_CAP=$(wc -l < "$T/reach_cap.txt" | tr -d ' ')

# --- emit markdown ---
hnd() { wc -l < "$T/hand_$1.txt" | tr -d ' '; }

cat <<EOF
# zioshade opcode/capability coverage matrix

> Generated by \`tools/coverage_matrix.sh\` (regenerable -- do not hand-edit). Methodology caveats in the script header.
> Universe = the \`Op\` enum in \`src/spirv.zig\` (**${OPN}** opcodes zioshade models). The SPIR-V core spec is larger (~310+); zioshade targets the shader-relevant subset.

## Per-backend static Op-opcode handling

| Backend | Statically handled | / modelled |
|---|---:|---:|
| HLSL | $(hnd hlsl) | ${OPN} |
| MSL  | $(hnd msl)  | ${OPN} |
| WGSL | $(hnd wgsl) | ${OPN} |
| GLSL | $(hnd glsl) | ${OPN} |

Handled by **all 4**: $(wc -l < "$T/all4.txt" | tr -d ' ').  Handled by **>=1**: $(wc -l < "$T/any.txt" | tr -d ' ').
"Handled" is a lower bound (distinct Op members the backend + shared-common code reference); real coverage is >= this. Authoritative corpus proof: \`tools/check_unhandled.zig\` reports **0 unhandled op** across tests/{glslang-430,spirv-cross,ghostty}.

## Empirical reach (${ok} real SPIR-V fixtures in tests/spirv_bins)

- **${REACH_OP}** distinct opcodes exercised; **${REACH_MODELLED}** modelled by zioshade.
- Exercised but NOT modelled: ${REACH_GAP:-none} (${REACH_GAP_COUNT} total -- trivial debug/metadata opcodes only; no shader-semantic opcode in the fixtures is unmodelled; "Image" maps to enum member OpImage).
- **${REACH_CAP}** distinct capabilities exercised: $(tr '\n' ' ' < "$T/reach_cap.txt")

## Modelled but not statically handled by any backend ($(wc -l < "$T/none.txt" | tr -d ' '))

$(tr '\n' ' ' < "$T/none.txt")

Sub-group: **module metadata** (Capability, Extension, ExtInstImport, MemoryModel) is processed structurally -- NOT a gap. The rest ($(grep -vcE 'Capability|Extension|ExtInstImport|MemoryModel' "$T/none.txt" | tr -d ' ')) are the real deferred areas: $(grep -vE 'Capability|Extension|ExtInstImport|MemoryModel' "$T/none.txt" | tr '\n' ' ')

## GLSLstd450 extended instructions

Universe: **${S450N}**. Per-backend static counts are omitted (GLSL/MSL/WGSL dispatch ExtInst by name, not enum arm -- a static count would misread 0). Corpus proof: \`check_unhandled.zig\` reports **0 unhandled std450**.

## Scope statement this matrix supports

zioshade models **${OPN}** Op opcodes; the real-fixture corpus exercises **${REACH_OP}** distinct opcodes, **${REACH_MODELLED}** of them modelled and handled (only debug-metadata unmodelled); the conformance corpora produce **0 unhandled** opcodes/std450. The correctness scope is therefore bounded and measurable, not implicit. Known deferred opcodes are enumerated above and each is a named honest-error, never silent-wrong.
EOF
