#!/usr/bin/env python3
"""Generate the per-opcode minimum word count table from the Khronos grammar.

The SPIR-V binary encoding puts a word count in the high half of every
instruction's first word. `parseModule` already checks that the count is
non-zero and does not run past the end of the buffer, but nothing checks that
an instruction is long enough to carry the operands its opcode requires. The
backend emit arms index `inst.words[2]`, `inst.words[3]`, `inst.words[4..]` and
so on with no per-arm guard, so a short instruction reads out of bounds.

The minimum is mechanical, so it is generated rather than transcribed:

    min = 1 + (number of operands with no quantifier)

A quantifier of '?' means optional and '*' means variadic, so neither kind
contributes to the minimum. Every remaining operand kind occupies at least one
word (a LiteralString is at least one word because of its NUL terminator, and a
LiteralContextDependentNumber is at least one word), so this is a true lower
bound and never over-constrains.

A hand-written version of this table got five opcodes wrong in the unsafe
direction (it rejected spec-valid modules), which is why the table is generated
and why it is keyed on the NUMERIC opcode from the grammar rather than on
zioshade's `spirv.Op` enum names. Keying on the number means a naming error in
`src/spirv.zig` cannot turn into a validation rule. There is one such error
today: `src/spirv.zig` names opcode 4432 `GroupNonUniformRotate`, but 4432 is
`OpSubgroupReadInvocationKHR`; `OpGroupNonUniformRotateKHR` is 4431.

Usage:

    # print the generated switch body
    python3 tools/gen_min_word_count.py

    # splice it into the marked region of the source file
    python3 tools/gen_min_word_count.py --write src/spirv_cross_common.zig

    # fail (exit 1) if the source file is out of date
    python3 tools/gen_min_word_count.py --check src/spirv_cross_common.zig

The grammar is read from the vendored copy next to this script
(tools/spirv.core.grammar.json), so generating and checking are both offline and
reproducible. Pass --grammar PATH for a different local copy, or --download to
refetch the pinned upstream revision over the network (which is how the vendored
copy is refreshed when the pin moves).
"""

import argparse
import json
import os
import sys
import urllib.request

# KhronosGroup/SPIRV-Headers, include/spirv/unified1/spirv.core.grammar.json
UPSTREAM_COMMIT = "29981f65241605e08b0ede4cfeb999fe3b723c6a"
UPSTREAM_URL = (
    "https://raw.githubusercontent.com/KhronosGroup/SPIRV-Headers/"
    + UPSTREAM_COMMIT
    + "/include/spirv/unified1/spirv.core.grammar.json"
)

# The vendored copy of the file at UPSTREAM_COMMIT. Committed so that neither
# regeneration nor the --check drift gate needs raw.githubusercontent.com.
VENDORED_GRAMMAR = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "spirv.core.grammar.json"
)

BEGIN = "    // BEGIN GENERATED by tools/gen_min_word_count.py, do not edit by hand."
END = "    // END GENERATED"


def load_grammar(path, download):
    if download:
        with urllib.request.urlopen(UPSTREAM_URL) as resp:
            return json.loads(resp.read())
    with open(path or VENDORED_GRAMMAR, "rb") as f:
        return json.load(f)


def minimums(grammar):
    """Map numeric opcode -> (minimum word count, opname).

    Aliases share an opcode; when that happens the smallest minimum wins, since
    accepting is always the safe direction for a length check.
    """
    out = {}
    for inst in grammar["instructions"]:
        opcode = inst["opcode"]
        n = 1 + sum(1 for o in inst.get("operands", []) if "quantifier" not in o)
        prev = out.get(opcode)
        if prev is None or n < prev[0]:
            out[opcode] = (n, inst["opname"])
    return out


def render(grammar):
    g = grammar
    version = "%d.%d rev %d" % (g["major_version"], g["minor_version"], g["revision"])
    mins = minimums(g)
    lines = [
        BEGIN,
        "    // Source: KhronosGroup/SPIRV-Headers commit " + UPSTREAM_COMMIT + ",",
        "    // include/spirv/unified1/spirv.core.grammar.json (SPIR-V " + version + ").",
        "    // Rule: min = 1 + (operands with no '?' or '*' quantifier).",
        "    // Keyed on the numeric opcode, never on a spirv.Op enum name.",
        "    return switch (@intFromEnum(op)) {",
    ]
    for opcode in sorted(mins):
        n, name = mins[opcode]
        lines.append("        %d => %d, // %s" % (opcode, n, name))
    lines.append("        else => null,")
    lines.append("    };")
    lines.append(END)
    return "\n".join(lines) + "\n"


def splice(source, generated):
    lines = source.splitlines(keepends=True)
    try:
        begin = next(i for i, l in enumerate(lines) if l.rstrip("\n") == BEGIN)
        end = next(i for i, l in enumerate(lines) if l.rstrip("\n") == END)
    except StopIteration:
        raise SystemExit("marker lines not found in the target file")
    if end < begin:
        raise SystemExit("END marker precedes BEGIN marker")
    return "".join(lines[:begin]) + generated + "".join(lines[end + 1 :])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--grammar",
        help="local spirv.core.grammar.json (default: the vendored tools/ copy)",
    )
    ap.add_argument(
        "--download",
        action="store_true",
        help="fetch the pinned upstream grammar over the network instead",
    )
    ap.add_argument("--write", metavar="FILE", help="splice the table into FILE")
    ap.add_argument("--check", metavar="FILE", help="exit 1 if FILE is out of date")
    args = ap.parse_args()

    if args.grammar and args.download:
        raise SystemExit("--grammar and --download are mutually exclusive")

    generated = render(load_grammar(args.grammar, args.download))

    target = args.write or args.check
    if not target:
        sys.stdout.write(generated)
        return 0

    with open(target, "r", encoding="utf-8") as f:
        source = f.read()
    updated = splice(source, generated)
    if args.check:
        if updated != source:
            sys.stderr.write("%s is out of date, rerun with --write\n" % target)
            return 1
        return 0
    if updated != source:
        with open(target, "w", encoding="utf-8") as f:
            f.write(updated)
        sys.stderr.write("updated %s\n" % target)
    else:
        sys.stderr.write("%s already up to date\n" % target)
    return 0


if __name__ == "__main__":
    sys.exit(main())
