#!/usr/bin/env bash
# Single source of truth for glslpp's status numbers (backlog #7).
#
# Generates docs/STATUS.md from a REAL conformance run — never hand-edited. The
# conformance suite (`zig build conformance`) validates every GLSL fixture's
# SPIR-V with spirv-val and is the project's trust baseline; this script parses
# its summary so docs can cite numbers that cannot silently go stale.
#
# Run:  just status      (or:  ZIG_CMD="mise exec -- zig" bash tools/gen_status.sh)
set -uo pipefail
cd "$(dirname "$0")/.."

ZIG_CMD=${ZIG_CMD:-"mise exec -- zig"}
OUT=docs/STATUS.md

echo "Running conformance (spirv-val gate) ..." >&2
conf=$($ZIG_CMD build conformance 2>&1)

num() { printf '%s\n' "$conf" | grep -E "$1" | grep -oE '[0-9]+' | tail -1; }
PASS=$(num '^PASS:');           PASS=${PASS:-?}
FAIL_SPV=$(num '^FAIL \(spirv\):');   FAIL_SPV=${FAIL_SPV:-?}
FAIL_CMP=$(num '^FAIL \(compile\):'); FAIL_CMP=${FAIL_CMP:-?}
SKIP=$(num '^SKIP:');           SKIP=${SKIP:-?}
XFAIL=$(num '^XFAIL:');          XFAIL=${XFAIL:-?}
TOTAL=$(num '^TOTAL:');          TOTAL=${TOTAL:-?}

COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
WHEN=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

cat > "$OUT" <<MD
<!-- GENERATED by \`just status\` (tools/gen_status.sh) from a real conformance
     run — DO NOT HAND-EDIT. Re-run \`just status\` to refresh. -->

# glslpp status

Generated: \`$WHEN\` · commit \`$COMMIT\`

## Conformance (\`zig build conformance\` — every fixture's SPIR-V validated with spirv-val)

| Metric | Count |
|--------|-------|
| PASS (spirv-val clean) | $PASS |
| FAIL (spirv-val) | $FAIL_SPV |
| FAIL (compile) | $FAIL_CMP |
| SKIP | $SKIP |
| XFAIL (known-unsupported, documented) | $XFAIL |
| **TOTAL** | **$TOTAL** |

The suite exits 0 when \`FAIL (spirv) == 0\` and \`FAIL (compile) == 0\`
(PASS + XFAIL + SKIP == TOTAL). XFAIL entries are the curated, documented
known-unsupported fixtures (\`tests/known-conformance-fails.txt\`), not silent
failures — glslpp honest-errors on them.

These numbers are authoritative; any conformance count quoted elsewhere in the
docs should be derived from this file (regenerate with \`just status\`).
MD

echo "Wrote $OUT (PASS=$PASS FAIL_spv=$FAIL_SPV FAIL_cmp=$FAIL_CMP SKIP=$SKIP XFAIL=$XFAIL TOTAL=$TOTAL)" >&2

# Non-zero exit if the trust gate is red, so CI/`just` surfaces it.
if [ "$FAIL_SPV" != "0" ] || [ "$FAIL_CMP" != "0" ]; then
  echo "error: conformance has real failures (FAIL_spv=$FAIL_SPV FAIL_cmp=$FAIL_CMP)" >&2
  exit 1
fi
