#!/usr/bin/env node
// WGSL BROWSER render oracle: execute zioshade's WGSL output in a REAL consumer
// WebGPU stack (Chrome + tint + Dawn, rasterized by SwiftShader) and diff the
// render against the Metal-proxy reference the wgsl-render gate uses.
//
// WHY THIS ORACLE EXISTS. The existing WGSL render proxy (tools/wgsl_render_check.sh)
// validates the WGSL by round-tripping naga -> SPIR-V -> spirv-cross MSL -> Metal. That
// confound was blind to the live P1 of bead zioshade-8k2: Chrome/tint REJECTED zioshade's
// WGSL at pipeline build ("textureSample must only be called from uniform control flow")
// while naga accepted it, so every text gate and every proxy gate passed and the wintty.io
// player silently fell back to black. Only a consumer stack (the real tint frontend, the
// real Dawn pipeline + binding validation, a real rasterizer) can see BOTH classes:
//   REJECT  tint/Dawn refuses the pipeline (the 8k2 class; surfaced with the verbatim
//           validation/compilation message)
//   FAIL    the pipeline builds, the shader runs, but the pixels are wrong (incl. the
//           silent-black fallback: black where the reference has content)
//
// HOW IT WORKS. Per shader, in one browser that stays up for the whole sweep:
//   1. source GLSL ->(glslang)-> src.spv
//   2. src.spv ->(zioshade wgsl)-> z.wgsl            [the output under test]
//   3. src.spv ->(spirv-cross --msl)-> ref.msl ->(ShaderCompare on Metal)-> reference PPM
//      (the same reference leg tools/wgsl_render_check.sh uses; ShaderCompare is invoked
//      with the SAME file on both legs so its _zioshade.ppm output IS the reference
//      render, generated by exactly the code path the proxy gate compares against)
//   4. z.wgsl -> the harness page (tools/wgsl_browser_harness.html) -> 3 frames on a
//      256x256 WebGPU canvas -> PAGE SCREENSHOT of the canvas element (WebGPU canvases
//      read back black via drawImage, so the screenshot is the only honest readback)
//      -> PNG decoded in-process (no dependencies; minimal 8-bit RGB/RGBA decoder)
//   5. pixel diff vs the reference (RGB, per channel)
//
// DETERMINISTIC UNIFORM STATE (single state for EVERY corpus, chosen once):
// the ShaderCompare GALLERY set at 256x256, because mid-animation cursor values
// matter (with the historical zero-cursor set the mode-change shaders short-circuit
// to their static path and their bug shapes never execute):
//     iResolution=(256,256,1)  iTime=1.7  iTimeDelta=1/60  iFrameRate=60  iFrame=102
//     iChannelTime[4]=0        iChannelResolution[4]=(256,256,1) each
//     iMouse=(64,64,64,64)     iDate=(2026,8,22,43200)    iSampleRate=48000
//     iCurrentCursor=(49,78,9,18)  iPreviousCursor=(159,122,18,18)   [a move in flight:
//         (iTime - iTimeCursorChange)/DURATION = 0.1, peak trail, the WARP-harness state]
//     cursor colors=(0.24,0.78,0.94,1)  styles=(0,0)  iCursorVisible=1
//     iTimeCursorChange=1.68  iTimeFocus=5.0  iFocus=1
//     iPalette[256] = HSV-ish ramp t=i/255 -> (t, tri(t), 1-t)
//     bg=(0.08,0.08,0.10) fg=(0.85,0.87,0.90) cursor=(0.24,0.78,0.94) cursorText=(0,0,0)
//     selFg=(1,1,1) selBg=(0.25,0.35,0.50)
//   iChannel0 = the ShaderCompare 256x256 reference texture (r=x*255/w, g=y*255/h,
//   b=(x^y)&255, integer division), linear/linear sampler.
//
// VERDICTS:
//   PASS        pipeline built, 3 frames rendered, diff within thresholds
//   REJECT      tint/Dawn refused (pipeline validation error or compile-info error);
//               the verbatim message is printed  [the 8k2 class]
//   FAIL        rendered but pixels diverge beyond thresholds, or the page died
//   LIVE-PASS   no reference available (ZWB_NO_REFERENCE=1, or the reference leg failed
//               for this shader): pipeline built + frames rendered + non-black coverage;
//               CLEARLY WEAKER, labeled as such (still catches every REJECT)
//   SKIP-*      the WGSL itself could not be produced (glslang refused the source
//               outside the gallery corpus, or a zioshade honest error)
//
// CROSS-GPU EPSILON. The proxy gate compares Metal-vs-Metal (maxdiff <= 1). This oracle
// compares SwiftShader-vs-Metal, so pure FP-ordering noise is wider; the thresholds below
// (MAXDIFF_PASS / BADPIX_PCT_PASS) were measured on the gallery corpus: benign
// cross-GPU divergence stays far below them, while the black-output negative control
// exceeds them by an order of magnitude.
//
// MODES / ENV:
//   ZWB_NO_REFERENCE=1       skip the Metal reference leg entirely; every shader is
//                            judged by the weaker LIVE-PASS assertions (loud banner)
//   ZWB_OVERRIDE_DIR=<dir>   per-shader negative control: if <dir>/<name>.wgsl exists,
//                            THAT text is rendered instead of the freshly compiled
//                            output (how the "broken WGSL must FAIL" proof is run; the
//                            staged outputs land in the share dir to hand-edit)
//   ZWB_SHARE=<dir>          staging + artifacts (default /tmp/zioshade_wgsl_browser);
//                            per shader: *.g.frag *.src.spv *.z.wgsl *.ref.msl
//                            *.shot.png (the screenshot) and *.browser.ppm (decoded)
//   ZWB_PLAYWRIGHT=<module>  playwright import path (default: bare 'playwright', then
//                            the known local install)
//   ZWB_CHROME=<path>        Chrome for Testing executable (the headless shell has no
//                            WebGPU; a full Chrome is required)
//
// SOURCE LEG: src.spv comes from glslang, an oracle independent of zioshade's
// frontend, for every corpus including the gallery. Gallery sources must compile
// under glslang verbatim (the corpus README invariant): a refusal there is a
// broken gallery entry and fails the gate, never a reason to stage the source
// through zioshade's own frontend (that lower-rigor leg would silently absorb
// the next real refusal into a frontend-correlated comparison). Outside the
// gallery corpus a glslang refusal stays a plain skip-glslang.
//
// BASELINE / GATE semantics (same style as tools/wgsl_render_baseline.txt):
// expected REJECT/FAIL entries are pinned in tools/wgsl_browser_baseline.txt, one per
// line, format "<corpus-dir>/<name>.frag: <reason>"; every entry MUST cite a reason.
// Exit 0 when every REJECT/FAIL is pinned, 1 on any NEW one. Regenerate with
// --update-baseline. The expectation for the gallery is 16/16 PASS with an EMPTY
// baseline; an entry there is a consumer-corpus regression.
//
// USAGE:
//   node tools/wgsl_browser_check.mjs [corpus dirs ...]   (default tests/wintty_gallery)
//   node tools/wgsl_browser_check.mjs --update-baseline [dirs]
//   node tools/wgsl_browser_check.mjs tests/wintty_gallery tools/wgsl_browser_fixtures
//
// NOT CI-SAFE: needs Chrome for Testing, a playwright import, node, and (for the
// reference leg) swiftc + Metal + glslang + spirv-cross. Manual only (`just wgsl-browser`).

import { spawnSync } from "node:child_process";
import { createServer } from "node:http";
import { inflateSync } from "node:zlib";
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const inRoot = (d) => (path.isAbsolute(d) ? d : path.join(ROOT, d));
const SHARE = process.env.ZWB_SHARE || "/tmp/zioshade_wgsl_browser";
const BASELINE = path.join(ROOT, "tools", "wgsl_browser_baseline.txt");
const HARNESS = path.join(ROOT, "tools", "wgsl_browser_harness.html");
const CLI = path.join(ROOT, "zig-out", "bin", "zioshade");
const RES = 256;

// Diff thresholds (see CROSS-GPU EPSILON above for how they were picked).
const MAXDIFF_PASS = 12;         // per-channel SwiftShader-vs-Metal FP noise ceiling
const BADPIX_PCT_PASS = 0.5;     // % of pixels with a per-pixel max-channel diff > 16
const LIVE_NONBLACK_MIN = 1.0;   // weaker liveness mode: >= 1% of pixels above luma 10

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

function die(msg) {
  console.error("error: " + msg);
  process.exit(2);
}

function run(cmd, args, opts = {}) {
  const r = spawnSync(cmd, args, { encoding: "buffer", maxBuffer: 1 << 28, ...opts });
  return { ok: r.status === 0, r };
}

function onPath(tool) {
  return spawnSync("/usr/bin/which", [tool]).status === 0;
}

const mtime = (p) => {
  try { return statSync(p).mtimeMs; } catch { return 0; }
};

// the proxy's layout rewrite: location-qualify the output declaration
function stageFragSource(srcPath, dstPath) {
  const text = readFileSync(srcPath, "utf8");
  writeFileSync(dstPath, text.replace(/^(out [a-z0-9]*vec4 [A-Za-z_][A-Za-z0-9_]*;)/m, "layout(location=0) $1"));
}

// ---------------------------------------------------------------------------
// PNG decode (8-bit RGB/RGBA, non-interlaced; the subset Chrome screenshots use)
// ---------------------------------------------------------------------------

function decodePng(buf) {
  const SIG = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
  if (buf.length < 8 || !buf.subarray(0, 8).equals(SIG)) throw new Error("not a PNG");
  let pos = 8;
  let w = 0, h = 0, bitDepth = 0, colorType = 0, interlace = 0;
  const idat = [];
  while (pos + 12 <= buf.length) {
    const len = buf.readUInt32BE(pos);
    const type = buf.toString("ascii", pos + 4, pos + 8);
    const data = buf.subarray(pos + 8, pos + 8 + len);
    pos += 12 + len;
    if (type === "IHDR") {
      w = data.readUInt32BE(0); h = data.readUInt32BE(4);
      bitDepth = data[8]; colorType = data[9]; interlace = data[12];
    } else if (type === "IDAT") idat.push(data);
    else if (type === "IEND") break;
  }
  if (bitDepth !== 8) throw new Error("unsupported PNG bit depth " + bitDepth);
  if (colorType !== 2 && colorType !== 6) throw new Error("unsupported PNG color type " + colorType);
  if (interlace) throw new Error("interlaced PNG unsupported");
  const bpp = colorType === 6 ? 4 : 3;
  const stride = w * bpp;
  const raw = inflateSync(Buffer.concat(idat));
  if (raw.length < h * (stride + 1)) throw new Error("truncated PNG data");
  const px = Buffer.alloc(w * h * 4);
  let prev = Buffer.alloc(stride);
  let p = 0;
  for (let y = 0; y < h; y++) {
    const filter = raw[p++];
    const cur = Buffer.from(raw.subarray(p, p + stride)); // copy: defilter in place
    p += stride;
    for (let x = 0; x < stride; x++) {
      const a = x >= bpp ? cur[x - bpp] : 0;
      const b = prev[x];
      const c = x >= bpp ? prev[x - bpp] : 0;
      let v = cur[x];
      if (filter === 1) v = (v + a) & 255;
      else if (filter === 2) v = (v + b) & 255;
      else if (filter === 3) v = (v + ((a + b) >> 1)) & 255;
      else if (filter === 4) {
        const pa = Math.abs(b - c), pb = Math.abs(a - c), pc = Math.abs(a + b - 2 * c);
        const pr = pa <= pb && pa <= pc ? a : pb <= pc ? b : c;
        v = (v + pr) & 255;
      } else if (filter !== 0) throw new Error("bad PNG filter " + filter);
      cur[x] = v;
    }
    for (let x = 0; x < w; x++) {
      const o = (y * w + x) * 4;
      px[o] = cur[x * bpp]; px[o + 1] = cur[x * bpp + 1]; px[o + 2] = cur[x * bpp + 2];
      px[o + 3] = bpp === 4 ? cur[x * bpp + 3] : 255;
    }
    prev = cur;
  }
  return { w, h, px };
}

// P3 (ASCII) PPM, what ShaderCompare saves
function parsePpm(text) {
  const tok = text.trim().split(/\s+/);
  if (tok[0] !== "P3") throw new Error("not a P3 PPM");
  const w = parseInt(tok[1], 10), h = parseInt(tok[2], 10);
  const n = w * h * 3;
  if (tok.length < 4 + n) throw new Error("truncated PPM");
  const px = Buffer.alloc(n);
  for (let i = 0; i < n; i++) px[i] = parseInt(tok[4 + i], 10) & 255;
  return { w, h, px };
}

// RGB diff of an RGBA buffer against an RGB reference
function compare(rgba, ref) {
  const n = rgba.w * rgba.h;
  let maxDiff = 0, sum = 0, bad = 0;
  for (let i = 0; i < n; i++) {
    const a = i * 4, b = i * 3;
    let pd = 0;
    for (let c = 0; c < 3; c++) {
      const d = Math.abs(rgba.px[a + c] - ref.px[b + c]);
      if (d > maxDiff) maxDiff = d;
      sum += d;
      if (d > pd) pd = d;
    }
    if (pd > 16) bad++;
  }
  return { maxDiff, avgDiff: sum / (n * 3), badPct: (100 * bad) / n };
}

function nonBlackPct(rgba) {
  let n = 0;
  for (let i = 0; i < rgba.w * rgba.h; i++) {
    const o = i * 4;
    if (rgba.px[o] > 10 || rgba.px[o + 1] > 10 || rgba.px[o + 2] > 10) n++;
  }
  return (100 * n) / (rgba.w * rgba.h);
}

// ---------------------------------------------------------------------------
// argument parsing + tool checks
// ---------------------------------------------------------------------------

let updateBaseline = false;
const dirs = [];
for (const a of process.argv.slice(2)) {
  if (a === "--update-baseline") updateBaseline = true;
  else if (a.startsWith("-")) die("unknown flag " + a);
  else dirs.push(a);
}
if (dirs.length === 0) dirs.push("tests/wintty_gallery");
for (const d of dirs) {
  if (!existsSync(inRoot(d))) die("corpus dir not found: " + d);
}
if (!existsSync(CLI)) die("build the CLI first (zig build cli / just wgsl-browser)");
mkdirSync(SHARE, { recursive: true });

const noReference = process.env.ZWB_NO_REFERENCE === "1";
const overrideDir = process.env.ZWB_OVERRIDE_DIR || null;

const SC = path.join(SHARE, "ShaderCompare");
if (!noReference) {
  for (const t of ["swiftc", "glslangValidator", "spirv-cross"]) {
    if (!onPath(t)) die("reference leg needs " + t + " on PATH (or set ZWB_NO_REFERENCE=1 for the weaker liveness mode)");
  }
  const scSrc = path.join(ROOT, "tools", "ShaderCompare.swift");
  // rebuild when the swift source is newer than the cached binary (stale-cache hazard)
  if (!existsSync(SC) || mtime(scSrc) > mtime(SC)) {
    if (!run("swiftc", ["-O", scSrc, "-o", SC]).ok) die("swiftc failed building ShaderCompare");
  }
}

// ---------------------------------------------------------------------------
// stage + reference generation (mirror of the proxy's legs)
// ---------------------------------------------------------------------------

function stageShader(dir, name) {
  const alias = path.basename(dir);
  const d = path.join(SHARE, alias + "." + name);
  stageFragSource(inRoot(dir) + "/" + name + ".frag", d + ".g.frag");
  const out = { key: dir + "/" + name + ".frag", d, wgsl: null, ref: null, skip: null, overridden: false, refused: false };

  const g = run("glslangValidator", ["-V", "-S", "frag", d + ".g.frag", "-o", d + ".src.spv"]);
  if (!g.ok) {
    // A gallery source glslang refuses is a broken gallery entry, not a
    // compiler verdict: it fails the gate loudly (see the staging loop)
    // instead of being skipped, pinned, or staged through a lower-rigor
    // source leg. Other corpora keep the historical skip.
    if (/wintty_gallery/.test(dir)) {
      out.refused = true;
    } else {
      out.skip = "skip-glslang";
    }
    return out;
  }

  const w = run(CLI, ["wgsl", d + ".src.spv", "--stage", "fragment"]);
  if (!w.ok) { out.skip = "skip-zwgsl"; return out; }
  out.wgsl = w.r.stdout.toString("utf8");
  writeFileSync(d + ".z.wgsl", out.wgsl);

  // negative-control hook: a hand-edited staged output replaces the compiled one
  if (overrideDir) {
    const ov = path.join(overrideDir, name + ".wgsl");
    if (existsSync(ov)) {
      out.wgsl = readFileSync(ov, "utf8");
      out.overridden = true;
    }
  }

  if (!noReference) {
    const refMsl = run("spirv-cross", ["--msl", d + ".src.spv"]);
    let rendered = false;
    if (refMsl.ok) {
      writeFileSync(d + ".ref.msl", refMsl.r.stdout);
      // Same file on both ShaderCompare legs: _zioshade.ppm is then exactly the
      // reference render the proxy gate diffs against, same uniforms + texture.
      const sc = run(SC, [d + ".ref.msl", d + ".ref.msl", d + ".refrender"], {
        env: { ...process.env, SHADERCOMPARE_GALLERY_UNIFORMS: "1", SHADERCOMPARE_RES: String(RES) },
      });
      const ppm = d + ".refrender_zioshade.ppm";
      if (sc.ok && existsSync(ppm)) {
        try {
          out.ref = parsePpm(readFileSync(ppm, "utf8"));
          rendered = true;
        } catch { /* fall through to the degraded verdict */ }
      }
    }
    // A reference-leg failure must NOT drop the shader: the browser leg still
    // proves tint acceptance, so judge it by the weaker LIVE assertions instead
    // (counted; the verdict line is labeled WEAKER).
    if (!rendered) out.noref = refMsl.ok ? "refrender-failed" : "crossmsl-failed";
  }
  return out;
}

// ---------------------------------------------------------------------------
// browser sweep
// ---------------------------------------------------------------------------

async function loadPlaywright() {
  const candidates = [
    process.env.ZWB_PLAYWRIGHT,
    "playwright",
    "/Users/alex/claude/baby-monitor/node_modules/playwright/index.mjs",
  ].filter(Boolean);
  for (const c of candidates) {
    try { return await import(c); } catch { /* try next */ }
  }
  die("playwright not importable; set ZWB_PLAYWRIGHT to its index.mjs");
}

const CHROME =
  process.env.ZWB_CHROME ||
  "/Users/alex/Library/Caches/ms-playwright/chromium-1234/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing";
if (!existsSync(CHROME)) die("Chrome for Testing not found at " + CHROME + " (set ZWB_CHROME)");

async function sweep(cases) {
  const pw = await loadPlaywright();
  let current = "";
  const server = createServer((req, res) => {
    if (req.url === "/case") {
      res.writeHead(200, { "content-type": "application/json" });
      res.end(JSON.stringify({ wgsl: current }));
      return;
    }
    res.writeHead(200, { "content-type": "text/html" });
    res.end(readFileSync(HARNESS));
  });
  await new Promise((r) => server.listen(0, "127.0.0.1", r));
  const url = "http://127.0.0.1:" + server.address().port + "/";

  const browser = await pw.chromium.launch({
    executablePath: CHROME,
    headless: true,
    args: ["--enable-unsafe-webgpu", "--enable-features=Vulkan", "--use-angle=swiftshader"],
  });
  const context = await browser.newContext({ viewport: { width: 420, height: 420 }, deviceScaleFactor: 1 });

  const results = [];
  try {
    for (const c of cases) {
      current = c.wgsl;
      const page = await context.newPage();
      const consoleLines = [];
      page.on("console", (m) => {
        if (m.type() === "error" || m.type() === "warning") consoleLines.push(m.type() + ": " + m.text());
      });
      page.on("pageerror", (e) => consoleLines.push("pageerror: " + e.message));
      const res = { reject: null, fail: null, img: null, frames: 0, adapter: null, console: null };
      try {
        await page.goto(url, { waitUntil: "domcontentloaded" });
        const handle = await page.waitForFunction(
          () => {
            if (window.__zwb && window.__zwb.settled) return window.__zwb;
            return false;
          },
          null,
          { polling: 100, timeout: 120000 },
        );
        const st = await handle.jsonValue();
        if (st.adapterInfo) {
          const ai = st.adapterInfo;
          res.adapter = [ai.vendor, ai.architecture].filter(Boolean).join("/") || "unknown";
        }
        if (st.fatal) {
          res.fail = "harness fatal: " + st.fatal;
        } else if (st.pipelineError || (st.compileErrors && st.compileErrors.length)) {
          const parts = [];
          if (st.pipelineError) parts.push(st.pipelineError);
          for (const m of st.compileErrors || []) parts.push("compile " + m);
          res.reject = parts.join(" | ");
        } else {
          const shot = await page.locator("#c").screenshot();
          writeFileSync(c.d + ".shot.png", shot);
          const img = decodePng(shot);
          if (img.w !== RES || img.h !== RES) {
            res.fail = "screenshot is " + img.w + "x" + img.h + ", expected " + RES + "x" + RES;
          } else {
            res.img = img;
            res.frames = st.framesRendered;
            // persist the decoded render next to the reference for debugging
            let ppm = "P3\n" + RES + " " + RES + "\n255\n";
            for (let y = 0; y < RES; y++) {
              const row = [];
              for (let x = 0; x < RES; x++) {
                const o = (y * RES + x) * 4;
                row.push(img.px[o] + " " + img.px[o + 1] + " " + img.px[o + 2]);
              }
              ppm += row.join(" ") + "\n";
            }
            writeFileSync(c.d + ".browser.ppm", ppm);
          }
        }
      } catch (e) {
        res.fail = "driver error: " + (e && e.message ? e.message : String(e));
      }
      if (consoleLines.length) res.console = consoleLines;
      results.push(res);
      await page.close();
    }
  } finally {
    await browser.close();
    server.close();
  }
  return results;
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------

const t0 = Date.now();
console.log("WGSL browser render oracle (Chrome + tint + Dawn on SwiftShader)");
console.log("  corpora: " + dirs.join(", "));
console.log("  share:   " + SHARE);
if (noReference) console.log("  MODE: ZWB_NO_REFERENCE=1 -> NO Metal reference; LIVE-PASS assertions only (WEAKER)");
if (overrideDir) console.log("  MODE: ZWB_OVERRIDE_DIR=" + overrideDir + " (negative control: staged overrides win)");
console.log("");

const staged = [];
const refused = [];
const counts = {};
const bump = (k) => (counts[k] = (counts[k] || 0) + 1);

for (const dir of dirs) {
  const files = readdirSync(inRoot(dir)).filter((f) => f.endsWith(".frag") && !f.includes(".asm."));
  for (const f of files) {
    const name = f.slice(0, -5);
    const s = stageShader(dir, name);
    if (s.refused) { refused.push(s.key); continue; }
    if (s.skip) { bump(s.skip); continue; }
    if (s.overridden) bump("overridden");
    if (s.noref) bump("noref-" + s.noref);
    staged.push({ name, key: s.key, d: s.d, wgsl: s.wgsl, ref: s.ref });
  }
}
if (staged.length === 0) die("no shader staged (all legs skipped or glslang-refused); refusing to report a vacuous green");

const browserResults = await sweep(staged);
const fails = [];

console.log("");
for (let i = 0; i < staged.length; i++) {
  const c = staged[i];
  const r = browserResults[i];
  let verdict, line = "";
  if (r.reject) {
    verdict = "REJECT";
    line = r.reject;
  } else if (r.fail) {
    verdict = "FAIL";
    line = r.fail;
  } else if (c.ref) {
    const m = compare(r.img, c.ref);
    line = "max=" + m.maxDiff + " avg=" + m.avgDiff.toFixed(4) + " bad=" + m.badPct.toFixed(3) + "%";
    if (m.maxDiff <= MAXDIFF_PASS && m.badPct <= BADPIX_PCT_PASS) verdict = "PASS";
    else {
      verdict = "FAIL";
      line += " (thresholds " + MAXDIFF_PASS + "/" + BADPIX_PCT_PASS + "%)";
    }
  } else {
    const nb = nonBlackPct(r.img);
    verdict = nb >= LIVE_NONBLACK_MIN && r.frames === 3 ? "LIVE-PASS" : "FAIL";
    line = "nonblack=" + nb.toFixed(1) + "% frames=" + r.frames + " [WEAKER: no reference]";
  }
  bump(verdict);
  console.log("  " + verdict.padEnd(9) + " " + c.key + "  " + line);
  if (verdict === "REJECT" || verdict === "FAIL") fails.push({ key: c.key, verdict, line });
  if (r.console) for (const cl of r.console.slice(0, 3)) console.log("            console: " + cl.slice(0, 240));
}

// ---- baseline: NEW REJECT/FAIL fails the gate; pinned ones pass with their reason ----
const base = new Map();
const baseOrder = [];
if (existsSync(BASELINE)) {
  for (const line of readFileSync(BASELINE, "utf8").split("\n")) {
    if (!line || line.startsWith("#")) continue;
    const p = line.indexOf(":");
    if (p < 0) continue;
    base.set(line.slice(0, p), line.slice(p + 1).trim());
    baseOrder.push(line.slice(0, p));
  }
}

let known = 0, stale = 0;
const saw = new Set();
console.log("");
for (const f of fails) {
  saw.add(f.key);
  const reason = base.get(f.key);
  if (reason) {
    known++;
    console.log("KNOWN-" + f.verdict + " " + f.key + " - accepted: " + reason);
  } else {
    console.log("NEW-" + f.verdict + "   " + f.key + " - " + f.line);
  }
}
for (const p of baseOrder) {
  const swept = dirs.some((d) => p.startsWith(d + "/"));
  if (swept && !saw.has(p)) {
    stale++;
    console.log("STALE       " + p + " - no longer fails; remove the entry from " + path.basename(BASELINE));
  }
}

if (updateBaseline) {
  const lines = [
    "# Expected REJECT/FAIL entries for tools/wgsl_browser_check.mjs (the WGSL browser oracle).",
    "# Format: <corpus-dir>/<name>.frag: <reason>",
    "# Every entry MUST cite a reason: a bug id, or triaged-and-accepted + why.",
    "# Regenerate: node tools/wgsl_browser_check.mjs --update-baseline   (see tool header.)",
    "# The wintty gallery corpus is expected EMPTY: 16/16 PASS on current main.",
    "",
  ];
  for (const p of [...baseOrder].sort()) {
    if (!dirs.some((d) => p.startsWith(d + "/"))) {
      lines.push(p + ": " + base.get(p)); // another corpus: pass through untouched
      continue;
    }
    if (saw.has(p)) {
      let reason = base.get(p) || "";
      if (!reason || reason.includes("REQUIRED")) {
        reason = "REQUIRED: triage this and cite a bug id or an accepted-why before committing";
      }
      lines.push(p + ": " + reason);
    }
  }
  for (const f of fails) {
    if (!base.has(f.key)) {
      lines.push(f.key + ": REQUIRED: triage this " + f.verdict + " and cite a bug id or an accepted-why before committing");
    }
  }
  writeFileSync(BASELINE, lines.join("\n") + "\n");
  console.log("baseline rewritten: " + BASELINE + " (fill every REQUIRED before committing)");
}

const newCount = fails.filter((f) => !base.has(f.key)).length;
console.log("");
console.log("=== WGSL browser oracle coverage ===");
for (const k of ["PASS", "LIVE-PASS", "REJECT", "FAIL", "overridden", "noref-crossmsl-failed", "noref-refrender-failed", "skip-glslang", "skip-zwgsl"]) {
  if (counts[k]) console.log("  " + k + ": " + counts[k]);
}
if (refused.length) {
  console.log("  GLSLANG-REFUSED (gate fail, gallery corpus): " + refused.length);
  for (const k of refused) console.log("    " + k + " - gallery sources must compile under glslang verbatim (broken gallery entry)");
}
const adapter = browserResults.map((r) => r.adapter).find(Boolean);
if (adapter) console.log("  adapter (first case): " + adapter);
console.log("  REJECT/FAIL known (baseline): " + known);
console.log("  REJECT/FAIL NEW (gate fail):  " + newCount);
if (stale) console.log("  baseline STALE entries:       " + stale + " (cleanup suggested)");
console.log("  runtime: " + ((Date.now() - t0) / 1000).toFixed(1) + "s");

if (newCount > 0 || refused.length > 0) {
  console.log("");
  console.log("WGSL BROWSER GATE: FAIL (" + newCount + " new REJECT/FAIL, " + refused.length + " glslang-refused source(s))");
  process.exit(1);
}
console.log("");
console.log("WGSL BROWSER GATE: PASS (no new rejections or render divergences; " + known + " known)");
