const std = @import("std");

pub const Op = enum(u16) {
    Nop = 0,
    Undef = 1,
    Source = 3,
    Name = 5,
    MemberName = 6,
    ExtInstImport = 11,
    Extension = 10,
    ExtInst = 12,
    MemoryModel = 14,
    EntryPoint = 15,
    ExecutionMode = 16,
    Capability = 17,
    TypeVoid = 19,
    TypeBool = 20,
    TypeInt = 21,
    TypeFloat = 22,
    TypeVector = 23,
    TypeMatrix = 24,
    TypeImage = 25,
    TypeSampler = 26,
    TypeSampledImage = 27,
    TypeArray = 28,
    TypeRuntimeArray = 29,
    TypeStruct = 30,
    TypePointer = 32,
    TypeFunction = 33,
    ConstantTrue = 41,
    ConstantFalse = 42,
    Constant = 43,
    ConstantComposite = 44,
    Function = 54,
    FunctionParameter = 55,
    FunctionEnd = 56,
    FunctionCall = 57,
    Variable = 59,
    Load = 61,
    Store = 62,
    AccessChain = 65,
    Decorate = 71,
    MemberDecorate = 72,
    VectorShuffle = 79,
    CompositeConstruct = 80,
    CompositeExtract = 81,
    SampledImage = 86,
    ImageSampleImplicitLod = 87,
    ImageSampleExplicitLod = 88,
    ImageSampleDrefImplicitLod = 89,
    ImageSampleDrefExplicitLod = 90,
    ImageSampleProjImplicitLod = 91,
    ImageSampleProjExplicitLod = 92,
    ImageSampleProjDrefImplicitLod = 93,
    ImageSampleProjDrefExplicitLod = 94,
    ImageFetch = 95,
    ImageGather = 96,
    ImageDrefGather = 97,
    OpImage = 100,
    VectorExtractDynamic = 77,
    ImageQuerySizeLod = 103,
    ImageQuerySize = 104,
    ImageQueryLevels = 106,
    ImageQuerySamples = 107,
    ImageRead = 98,
    ImageWrite = 99,
    ImageTexelPointer = 101,
    AtomicIAdd = 234,
    AtomicISub = 235,
    AtomicSMin = 236,
    AtomicUMin = 237,
    AtomicSMax = 238,
    AtomicUMax = 239,
    AtomicAnd = 240,
    AtomicOr = 241,
    AtomicXor = 242,
    AtomicExchange = 244,
    AtomicCompareExchange = 247,
    Transpose = 84,
    ConvertFToS = 110,
    ConvertSToF = 111,
    ConvertUToF = 112,
    ConvertFToU = 109,
    ConvertSToU = 114,
    ConvertUToS = 115,
    IsNan = 156,
    IsInf = 157,
    All = 154,
    Any = 155,
    Bitcast = 124,
    SNegate = 126,
    FNegate = 127,
    IAdd = 128,
    FAdd = 129,
    ISub = 130,
    FSub = 131,
    IMul = 132,
    FMul = 133,
    FMod = 141,
    UDiv = 134,
    SDiv = 135,
    FDiv = 136,
    UMod = 137,
    SRem = 138,
    FRem = 140,
    VectorTimesScalar = 142,
    MatrixTimesScalar = 143,
    VectorTimesMatrix = 144,
    MatrixTimesVector = 145,
    MatrixTimesMatrix = 146,
    OuterProduct = 147,
    Dot = 148,
    DPdx = 207,
    DPdy = 208,
    Fwidth = 209,
    LogicalOr = 166,
    LogicalAnd = 167,
    LogicalNot = 168,
    Select = 169,
    IEqual = 170,
    INotEqual = 171,
    UGreaterThan = 172,
    SGreaterThan = 173,
    UGreaterThanEqual = 174,
    SGreaterThanEqual = 175,
    ULessThan = 176,
    SLessThan = 177,
    ULessThanEqual = 178,
    SLessThanEqual = 179,
    FOrdEqual = 180,
    FOrdNotEqual = 182,
    FOrdLessThan = 184,
    FOrdGreaterThan = 186,
    FOrdLessThanEqual = 188,
    FOrdGreaterThanEqual = 190,
    ShiftRightLogical = 194,
    ShiftRightArithmetic = 195,
    ShiftLeftLogical = 196,
    BitwiseOr = 197,
    BitwiseXor = 198,
    BitwiseAnd = 199,
    Not = 200,
    SubgroupAllKHR = 4428,
    SubgroupAnyKHR = 4429,
    SubgroupAllEqualKHR = 4430,
    LoopMerge = 246,
    SelectionMerge = 247,
    Label = 248,
    Branch = 249,
    BranchConditional = 250,
    Kill = 252,
    Return = 253,
    ReturnValue = 254,
    Unreachable = 255,
    _,
};

pub const Capability = enum(u32) {
    shader = 1,
    sampled_image_array_dynamic_indexing = 2,
    image_cube_array = 3,
    sample_rate_shading = 5,
    image_query = 50,
    sampled_buffer = 46,
    image_buffer = 47,
    image_ms_array = 48,
    storage_image_multisample = 27,
    group_vote = 44,
    subgroup_vote_khr = 4431,
    _,
};

pub const BuiltIn = enum(u32) {
    position = 0,
    point_size = 1,
    vertex_index = 5,
    instance_index = 6,
    layer = 9,
    view_index = 10,
    frag_coord = 15,
    front_facing = 17,
    sample_position = 19,
    sample_mask = 20,
    helper_invocation = 23,
    num_workgroups = 24,
    workgroup_size = 25,
    workgroup_id = 26,
    local_invocation_id = 27,
    global_invocation_id = 28,
    local_invocation_index = 29,
    base_vertex = 4424,
    device_index = 4440,
    _,
};

pub const ExecutionModel = enum(u32) {
    Vertex = 0,
    TessellationControl = 1,
    TessellationEvaluation = 2,
    Geometry = 3,
    Fragment = 4,
    GLCompute = 5,
    _,
};

pub const StorageClass = enum(u32) {
    UniformConstant = 0,
    Input = 1,
    Uniform = 2,
    Output = 3,
    Workgroup = 4,
    CrossWorkgroup = 5,
    Private = 6,
    Function = 7,
    Generic = 8,
    PushConstant = 9,
    StorageBuffer = 12,
    _,
};

pub const Decoration = enum(u32) {
    block = 2,
    row_major = 3,
    built_in = 11,
    array_stride = 6,
    matrix_stride = 7,
    location = 30,
    binding = 33,
    descriptor_set = 34,
    offset = 35,
    _,
};

pub const ExecutionMode = enum(u32) {
    OriginUpperLeft = 7,
    LocalSize = 17,
    _,
};

pub const GLSLstd450 = enum(u32) {
    Round = 1,
    RoundEven = 2,
    Trunc = 3,
    FAbs = 4,
    FSign = 6,
    Floor = 8,
    Ceil = 10,
    Fract = 12,
    Radians = 14,
    Degrees = 16,
    Sin = 18,
    Cos = 20,
    Tan = 22,
    Asin = 24,
    Acos = 26,
    Atan = 28,
    Atan2 = 30,
    Sinh = 32,
    Cosh = 34,
    Tanh = 36,
    Asinh = 38,
    Acosh = 40,
    Atanh = 42,
    Pow = 48,
    Exp = 50,
    Log = 52,
    Exp2 = 54,
    Log2 = 56,
    Sqrt = 58,
    InverseSqrt = 60,
    Abs = 62,
    Sign = 64,
    FMin = 72,
    FMax = 74,
    FClamp = 76,
    FMix = 78,
    Step = 80,
    SmoothStep = 82,
    Length = 84,
    Distance = 86,
    Cross = 88,
    Normalize = 90,
    FaceForward = 92,
    Reflect = 94,
    Refract = 96,
    Determinant = 100,
    MatrixInverse = 102,
    _,
};

pub const MAGIC: u32 = 0x07230203;

pub fn encodeInstructionHeader(word_count: u16, opcode: u16) u32 {
    return (@as(u32, word_count) << 16) | opcode;
}

pub fn encodeVersion(major: u8, minor: u8, patch: u8) u32 {
    return (@as(u32, major) << 16) | (@as(u32, minor) << 8) | patch;
}

test "instruction header encoding" {
    const header = encodeInstructionHeader(3, 54);
    try std.testing.expectEqual(@as(u32, 0x00030036), header);
}

test "magic number" {
    try std.testing.expectEqual(@as(u32, 0x07230203), MAGIC);
}

test "version encoding" {
    try std.testing.expectEqual(@as(u32, 0x00010500), encodeVersion(1, 5, 0));
}

test "opcode values match SPIR-V spec" {
    try std.testing.expectEqual(@as(u16, 249), @intFromEnum(Op.Branch));
    try std.testing.expectEqual(@as(u16, 253), @intFromEnum(Op.Return));
    try std.testing.expectEqual(@as(u16, 254), @intFromEnum(Op.ReturnValue));
    try std.testing.expectEqual(@as(u16, 57), @intFromEnum(Op.FunctionCall));
    try std.testing.expectEqual(@as(u16, 128), @intFromEnum(Op.IAdd));
    try std.testing.expectEqual(@as(u16, 169), @intFromEnum(Op.Select));
    try std.testing.expectEqual(@as(u16, 200), @intFromEnum(Op.Not));
}